### PR TITLE
added playback control to the default audio player controls

### PR DESCRIPTION
**Pull request by ebukaodini**
This allows the audio player to come with playback support by default

### CODE REVIEW

**Comment by tneotia** [comment]
Added in #12 with the merge of chewie 1.0.0 into this library. Thanks for the PR though! :)

**Comment by erickok** [comment]
Thanks again for the contribution. So if @tneotia can confirm with the chewie 1.0 merge we already offer this feature now, right?

**Comment by tneotia** [comment]
Yes that is correct. You can now set playback control parameters, and they are shown by default.

**Comment by erickok** [comment]
Thanks. Then @ryan-berger can close this one.

**Pull request closed without merging**
